"""Init DataBase

Revision ID: a65b06d6c7e3
Revises: 
Create Date: 2024-06-04 23:43:59.480514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65b06d6c7e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_price_stream',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('event_time', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('interval', sa.VARCHAR(length=5), nullable=True),
    sa.Column('avg_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('last_trade_time', sa.BigInteger(), nullable=True),
    sa.Column('usdt_to_usd', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_price_stream_symbol'), 'average_price_stream', ['symbol'], unique=False)
    op.create_table('book_ticker_stream',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('best_bid', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('bid_qty', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('best_ask', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('asq_qty', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('usdt_to_usd', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_ticker_stream_symbol'), 'book_ticker_stream', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_ticker_stream_symbol'), table_name='book_ticker_stream')
    op.drop_table('book_ticker_stream')
    op.drop_index(op.f('ix_average_price_stream_symbol'), table_name='average_price_stream')
    op.drop_table('average_price_stream')
    # ### end Alembic commands ###
